// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Musicly.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Persistence.Migrations.InitialModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201608031134575_InitialModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
